language: node_js
node_js:
  - 8

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn global add lerna@2.5.1
  - yarn
  - lerna bootstrap

script:
  - yarn test

notifications:
  email: false
